### ISSUE TITLE
See what you can add to the readme file

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/ListBot#1]

**Comment by manishkrjha** [comment]
Hey @tomassirio , I was thinking of adding a contributor checklist where we can mention the steps one needs to follow to contribute to raise a PR to this project.

It will go as
- Fork Repository
- Clone
- Make your own branch (with some regulations on branch name like changes/username)
- signing off commits
- pushing it to repository.

**Comment by tomassirio** [comment]
Pls do!
