### ISSUE TITLE
[BUG] The devMongoURL string is broken

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/ListBot#117]
As apointed by @rgroves:

> Also, it looks like the code base is in a somewhat broken state. I had to modify src\commands\polls.js to remove an error and modify the devMongoUrl connection string in src\config\index.js. (Note: I was not using Docker)

**Comment by rgroves** [comment]
Do you have a preference as to how to go about fixing this?

My proposal is as follows:

- Add two new environment variables: `LOCAL_DB_HOST` (required), `LOCAL_DB_PORT` (optional)
- Add some logic to `src/config/index.js` construct the appropriate connection string (similar to what is already being done in .env.example, but with some checks for if the optional port is provided to add the necessary `:port` to the string)

This could also be utilized for the production url too, if say there were a corresponding `DB_HOST` and `DB_PORT` variables for production.

Currently the `.env.example` doesn't mention anything about the production variables. Maybe some comments can be added to the `.env.example` as well to document the settings.

Let me know if you'd like me to pick this one up and any input you might have on it for which direction to take.

**Comment by tomassirio** [comment]
Let's go that way. I don't have a preference for the env variables right now

**Comment by rgroves** [comment]
What do you think about standardizing the config settings of `LOCAL_DB_PASSWORD` and `DB_PASS` so that the last part matches between the two. So either making it:

`LOCAL_DB_PASS` and `DB_PASS`
...or...
`LOCAL_DB_PASSWORD` and `DB_PASSWORD`

I favor the second set with password spelled out, but that would be a breaking difference in production settings of current bot users.

**Comment by tomassirio** [comment]
I'd go with the second one as well. Env variables should be as declarative as possible
