### ISSUE TITLE
[BUG] Fix the linting checks for the github actions module

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/ListBot#118]
As appointed by @rgroves:

> It also looks like linting checks may have been modified or added, because it looks like files that weren't part of my PR changes are failing checks. Let me know how to proceed or if this is fine. Thanks!

**Comment by rgroves** [comment]
I'll take this one.

**Comment by tomassirio** [comment]
Sure! i'll assign it to you then

**Comment by tomassirio** [comment]
@rgroves 

```
Run npm run lint

> ListBot@3.1.0 lint /home/runner/work/ListBot/ListBot
> eslint .


/home/runner/work/ListBot/ListBot/src/commands/poll.js
  127:1  error  Parsing error: Unexpected token }

✖ 1 problem (1 error, 0 warnings)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ListBot@3.1.0 lint: `eslint .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ListBot@3.1.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-10-15T22_39_57_919Z-debug.log
Error: Process completed with exit code 1.
```

I had an issue with the lint fixes after merging your changes

**Comment by rgroves** [comment]
@tomassirio  I mentioned that in the [PR comment](https://github.com/tomassirio/ListBot/pull/120#issue-504371184). The file poll.js is failing linting because it has a bunch of problems that aren't really linting related, but syntax/logic related.

I'm working on #119  now that will fix up poll.js and make polls work.

**Comment by tomassirio** [comment]
My bad. Closing this issue
