### ISSUE TITLE
[BUG] Poll is broken

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/ListBot#119]
> 2020-10-15T12:29:17.044062+00:00 app[worker.1]: /app/src/commands/poll.js:127
> 2020-10-15T12:29:17.044089+00:00 app[worker.1]: }
> 2020-10-15T12:29:17.044089+00:00 app[worker.1]: ^
> 2020-10-15T12:29:17.044089+00:00 app[worker.1]: 
> 2020-10-15T12:29:17.044090+00:00 app[worker.1]: SyntaxError: Unexpected token '}'
> 2020-10-15T12:29:17.044091+00:00 app[worker.1]: at wrapSafe (internal/modules/cjs/loader.js:979:16)
> 2020-10-15T12:29:17.044091+00:00 app[worker.1]: at Module._compile (internal/modules/cjs/loader.js:1027:27)
> 2020-10-15T12:29:17.044138+00:00 app[worker.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
> 2020-10-15T12:29:17.044139+00:00 app[worker.1]: at Module.load (internal/modules/cjs/loader.js:928:32)
> 2020-10-15T12:29:17.044140+00:00 app[worker.1]: at Function.Module._load (internal/modules/cjs/loader.js:769:14)
> 2020-10-15T12:29:17.044140+00:00 app[worker.1]: at Module.require (internal/modules/cjs/loader.js:952:19)
> 2020-10-15T12:29:17.044140+00:00 app[worker.1]: at require (internal/modules/cjs/helpers.js:88:18)
> 2020-10-15T12:29:17.044141+00:00 app[worker.1]: at module.exports (/app/src/handlers/command.js:12:22)
> 2020-10-15T12:29:17.044141+00:00 app[worker.1]: at /app/src/index.js:16:37
> 2020-10-15T12:29:17.044141+00:00 app[worker.1]: at Array.forEach (<anonymous>)
> 2020-10-15T12:29:17.044142+00:00 app[worker.1]: at Object.<anonymous> (/app/src/index.js:14:14)
> 2020-10-15T12:29:17.044142+00:00 app[worker.1]: at Module._compile (internal/modules/cjs/loader.js:1063:30)
> 2020-10-15T12:29:17.044142+00:00 app[worker.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
> 2020-10-15T12:29:17.044142+00:00 app[worker.1]: at Module.load (internal/modules/cjs/loader.js:928:32)
> 2020-10-15T12:29:17.044143+00:00 app[worker.1]: at Function.Module._load (internal/modules/cjs/loader.js:769:14)
> 2020-10-15T12:29:17.044149+00:00 app[worker.1]: at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
> 2020-10-15T12:29:17.117259+00:00 heroku[worker.1]: Process exited with status 1
>

**Comment by rgroves** [comment]
If no one else is looking into this one, I can take a shot at fixing it.

**Comment by tomassirio** [comment]
Sure! I'll assign it to you

**Comment by rgroves** [comment]
I'm about to submit a PR for this issue. I took it in a slightly different direction than where it was at and made some assumptions, but it's a start and provides basic poll functionality which can be tweaked in the future.
