### ISSUE TITLE
Format the list command output

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/ListBot#13]
The list command output looks kind of bad. See if you can make it any better

**Comment by Oatelaus** [comment]
I'm gonna pick this up, if that's okay!

**Comment by tomassirio** [comment]
Sure!

**Comment by JDOG787** [comment]
Hi, would it de ok if I tried this out too?

**Comment by Oatelaus** [comment]
@JDOG787 I've done the original issue already. 

I was going to add strike through functionality, so you can mark items in the list as done.

You would need to...

1. Add a flag to the model so we can save state in the database.
2. Add a command to mark items as done
3. Add `~` surrounding the value of done items within `list.js`.
