### ISSUE TITLE
[BUG] Remove Unused Code

### ISSUE THREAD

**Issue by rgroves** [tomassirio/ListBot#135]
**Describe the bug**
It seems that after some of the refactoring that's been performed recently, the code in `src/commands/info/commands.js` is no longer in use. It makes sense to delete this file from the repo.

**Comment by rgroves** [comment]
@tomassirio maybe give this one the easy and good first issue labels and let a beginner pick it up.

**Comment by tomassirio** [comment]
Sure! thanks @rgroves

**Comment by RazCrimson** [comment]
@tomassirio Can I be assigned this?

**Comment by Johnisaig** [comment]
Hi, can I work on this ?

**Comment by tomassirio** [comment]
It will be a race to the top I guess

**Comment by RazCrimson** [comment]
Making my first PR, is this the right way to do it?
