### ISSUE TITLE
[BUG] Issues with the Add, Remove and Multi-remove commands

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/ListBot#147]
1- Add command adds an empty string to the list if user doesn't provide any argument.
2- Remove command replies with "Successfully deleted item of index NaN" if user doesn't provide any argument.
3- Multi-remove command replies with "Successfully deleted items from index NaN to NaN".

**Comment by vitasenka** [comment]
I can do it.

**Comment by tomassirio** [comment]
Sure!

**Comment by rgroves** [comment]
The `$remove` bug is particularly nasty, because it does actually remove the first item in the list.

Hey @vitasenka, 👋 are you still working on this issue?

**Comment by vitasenka** [comment]
@rgroves It's almost done. I was waiting for other contributors to finish the styling.
