### ISSUE TITLE
[FEATURE] Increase poll range of choices

### ISSUE THREAD

**Issue by RazCrimson** [tomassirio/ListBot#150]
**Is your feature request related to a problem? Please describe.**
The bot currently only supports polls with 5 choices. Also some minor redundant initialization and variables in poll.js

**Describe the solution you'd like**
Increase the range of choices by adding 6-9 and possibly A-Z emotes too. So it will be 1-9, A-Z to a total of 35 possible choices to vote on.

**Describe alternatives you've considered**
We can maybe just add until 9, but that will be too low incase the list in big.

**Comment by rgroves** [comment]
@RazCrimson can you point out the redundant initializations/variables that you've noticed? Wondering if we should address that as a separate code quality issue.

@tomassirio do you have an opinion on how this should work? Would the number of options be an option on the $poll command so a user can choose how many random items they want in the poll? Or should it just be increased to 9 items with no option to specify?

**Comment by tomassirio** [comment]
Maybe we can have a parameter for the number of options. It could be default initialized to 5

**Comment by rgroves** [comment]
Sounds good to me. Thanks for the input.

@RazCrimson if you haven't started working on this already feel free to proceed with making the default 5 and allowing the user to pass an option to indicate the number of items in the poll, from 2 to a max of 9 for now. 

Maybe in the future we can introduce paging into the bot messages for longer lists and at that point we can decide how to handle a poll with more than 9, if it makes sense (I could see it getting messy with the number of emoji reacts on a very large poll though).

**Comment by RazCrimson** [comment]
@rgroves Will add a parameter with 5 being the default, allowing a range of 2-9. 
It selects the first N elements? If so we might need a PR/Issue to re order the list items.

As for the redundant initializations, it was  Webstorm reporting to me while I made commits. We should have like half a dozen or so redundant initializations and the `minutes` variable being assigned 0 in line number 72 of `poll.js` had no effect at all.

I will check the code base later and open another issue if there are other stuff like this.

**Comment by rgroves** [comment]
Regarding the item order, it pulls back all items from the database  on line 12 and does a random shuffle on line 17 before pulling the first N elements of the shuffled list.

I agree that the assignment on line 72 is unnecessary. I'll open an issue for code quality/optimization and assign it to you.
