### ISSUE TITLE
Improve the project setup

### ISSUE THREAD

**Issue by javleds** [tomassirio/ListBot#16]
I have noticed that the project require some extra steps to be executed in local environments, as well, as some good practices that we could implement in here.

I have created a PR with 3 main changes:
- Add a `.env.example` file to store the constants of the project, this will allow you to have your own copy of `.env` file with your personal information.
- Remove `node_modules` from the git repository, since it could be easilly installes by running the `npm install` or `yarn install` command, also, the node_modules is the bigger in all the project.
- Create a USE_DOCKER_FOR_DEVELOP environment constant, which will change the manual change of the database connection.

The PR with this changes is this one: https://github.com/tomassirio/ListBot/pull/15

**Comment by Oatelaus** [comment]
Can I suggest using process.env.NODE_ENV? Otherwise you'll be stacking up `USE_[FEATURE]_FOR_DEVELOP` flags. This way you can set it via the run command

**Comment by javleds** [comment]
@Fedelaus the pull request was already merged, but your suggestion is awesome, do you want to perform the change in a new PR?

**Comment by tomassirio** [comment]
@javleds @Fedelaus is this issue ready to be closed? Was a new PR opened for @Fedelaus proposal?

**Comment by Oatelaus** [comment]
All done
