### ISSUE TITLE
[BUG] The help command's output does not provide help for all commands currently available.

### ISSUE THREAD

**Issue by ahmad-reza619** [tomassirio/ListBot#160]
**Describe the bug**
Currently there is no description about promote & demote command in $help command.

**To Reproduce**

1. Type $help & enter
2. No desc about promote & demote command

**Expected behavior**
There should be description about this command

**Additional context**
For the description of command:
1. Promote: add admin for Listbot command. Note that owner of the server is automatically assigned the role admin of ListBot
2. Demote: remove admin from Listbot

**PS**: sorry for my bad english, if there is a better grammar or words for this, please do write those instead of this

**Comment by rgroves** [comment]
I'm going to edit the description of this issue because the help command needs more entries than just promote and demote added. Currently these commands are missing from the help list and need to be added:
-   demote
-   promote
-   clear
-   ping
