### ISSUE TITLE
The Poll command has a bug on the polling results

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/ListBot#2]
Basically the poll never shows the results given the votes on the emojis

**Comment by heyimalaap** [comment]
Ah do you mean for polls with time limits? I could maybe have a go at this.

**Comment by tomassirio** [comment]
Thanks! Have fun

**Comment by tomassirio** [comment]
@heyimalaap is this issue closed?

**Comment by heyimalaap** [comment]
will pr the fix soon
