### ISSUE TITLE
Repeated code in almost all the commands

### ISSUE THREAD

**Issue by javleds** [tomassirio/ListBot#21]
In almost all the commands exists a validation for the channel existence, if it does not exists, then it create it, what you think if abstract that code in a util to re-use it in all needed places?

![image](https://user-images.githubusercontent.com/11241239/95023523-2b105c00-0643-11eb-989a-17684e2fbaf9.png)

**Comment by tomassirio** [comment]
Definetely is the way i'd have gone. I'm fairly new to node.js and i couldn't find my way around as I normally do in Java. If you think you can abstract those methods I'd be thankfull to check that PR

**Comment by javleds** [comment]
Nice, I will create a PR for this one, I just have a question, is this repo be executed in a modern javascript engine? Or what versión of nodejs are you using?

**Comment by tomassirio** [comment]
I'm running this on node 6.14.7

**Comment by javleds** [comment]
The pull request is done: https://github.com/tomassirio/ListBot/pull/25

I am working into implement babel, in order to allow to run the script in any node version.
