### ISSUE TITLE
Wrap the code to be compatible with node 6

### ISSUE THREAD

**Issue by javleds** [tomassirio/ListBot#29]
Latest features of NodeJS, also known as EcmaScript 2017 and above, won't work in older versions than Node 8.0, in order to run scripts with all the features available, we should wrap the code using babel and polyfill.

The idea is the follwoing:
- Move all the `javascript` files to the `src` directory.
- Install babel and polyfill as dependencies of the project.
- For development proposes no changes will needed.
- For deployment, we should change the script with the following changes:
  1. The environment should forced to be `production` in order to connect with the real mognodb parameters.
  2. The `src` directory should be transpiled into the `build` directory using babel an polyfill.

**Comment by javleds** [comment]
Pull request for this is ready to review: https://github.com/tomassirio/ListBot/pull/28

If you have any question about why this change was done, feel free to ask.

**Comment by Oatelaus** [comment]
What's gained by the added by the build/babel step? It's not being packaged into a non-node environment, so it doesn't really make sense (to me)

**Comment by javleds** [comment]
Hi @Fedelaus! It does not looks relevant for latest versions of nodejs, but https://github.com/tomassirio/ListBot/issues/21#issuecomment-703295601 in that comment @tomassirio affirms the usage of older versions of nodejs which has a lot of missing capabilities, you can see more about that in here:  https://node.green/

What do you think about it?

**Comment by Oatelaus** [comment]
@javleds I think @tomassirio posted `npm -v` and not `node -v`, as `6.14.7` was the latest version of `npm` at the time of his comment - node 6 also outdates this project by a huge amount. 

Outside of this, I think...

1. Adding a build chain for an out of support version of node is a little backwards. The project should be brought up to the latest supported version and maintainers should update their systems to match.

2. We don't get any enhancements from babel which couldn't be gained from just upgrading the node version at project/system level.

As we aren't moving to a different environment I don't see the need for poly-fills currently.

**Comment by javleds** [comment]
I Agree, part of our work is to keep the latest versions of the tools that are using, but sometimes it requires more than a single `npm i -g`.

We achieve 2 things with this PR, one of them is to wrap the project into the `src` directory, and the second one is to give support for old versions. Polyfill is used to fill the red squares shared into the page above. 

Once we are sure that older support is not needed, we only need to remove babel/polyfill dependencies and point the start command back to the `src` directory.

Is not a big deal, but I think, by now we could keep it. Is up to you @tomassirio @Fedelaus

**Comment by Oatelaus** [comment]
I'm going to add the opposite PR, as I think this adds more pain and the original issue it addresses was a misunderstanding. I think it's better people update their systems than add support for versions Node no longer support themselves.

Agree with adding it into a src directory though.
