### ISSUE TITLE
Command refactor

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/ListBot#3]
The bot is really sloppy since it was a hobby project. If you want to change something or make something look better, then give it a try

**Comment by jayeshmann** [comment]
Can you assign me to this?

**Comment by tomassirio** [comment]
Sure @jayeshmann

**Comment by rgroves** [comment]
Hey @tomassirio  did PR #3 address this issue in full so we can close it? If not, what else is needed?

**Comment by tomassiriouala** [comment]
Nothing else. I forgot to close the issue
