### ISSUE TITLE
Remove command not working correctly

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/ListBot#34]
Comes from a discussion on Issue [#27 ](https://github.com/tomassirio/ListBot/issues/27)

Apparently the remove command is not removing the element associated to the DB

**Comment by Croustys** [comment]
Would like to try contributing to it myself!

**Comment by JStruk** [comment]
I can take a look at this issue, mind assigning it to me? I'll have a PR up by end-of-day 😄

**Comment by tomassirio** [comment]
Sure Bud

**Comment by JStruk** [comment]
If this issue has been fixed as part of #38 I'll disregard and won't put a PR up 😄

**Comment by tomassirio** [comment]
It wasn't resolved yet. However, let's give JDOG a chance and if he can't solve it then you can take it

**Comment by JDOG787** [comment]
Im trying to figure it out.

**Comment by tomassirio** [comment]
@JDOG787 see if [this](https://www.earthdatascience.org/courses/intro-to-earth-data-science/git-github/github-collaboration/update-github-repositories-with-changes-by-others/) helps you sort the issue out. I often need the issues being drawn in order to fully understand the issue

**Comment by JDOG787** [comment]
@tomassirio Ok ill look at it thx

**Comment by JDOG787** [comment]
@tomassirio ok so I think it makes more sense now. But will I need to close the current pull request to do the reverse pull request?

**Comment by tomassirio** [comment]
Hmm, I don't think you should. Give it a try, what I think will happen is that you will need to commit your changes among the pull request to the other pull request so you should be fine

**Comment by JDOG787** [comment]
Hmmmm well this is what I see when I click make pull request on my fork 
![Screen Shot 2020-10-05 at 3 48 29 PM](https://user-images.githubusercontent.com/64325143/95139869-57e77080-0722-11eb-9951-44478b6fc05d.png)

Any ideas?

**Comment by JDOG787** [comment]
Going to try to close it first.

**Comment by JDOG787** [comment]
wow I think it might be working. ill let you know

**Comment by JDOG787** [comment]
@tomassirio ok I think I got it

**Comment by RazCrimson** [comment]
@tomassirio Is this still up for grabs?

**Comment by tomassirio** [comment]
I'm not sure. Do you want to try it anyways?

**Comment by RazCrimson** [comment]
Thx

**Comment by RazCrimson** [comment]
@tomassirio I wasn't able to reproduce the issue. I guess, its either fixed or needs more than one user to appear.

**Comment by tomassirio** [comment]
It might have been fixed. If you checked and it's working, then i'll close the issue. Thanks @RazCrimson
