### ISSUE TITLE
Add your user to the contribution list in the Readme

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/ListBot#40]
Easy for beginners. This is all about lists in the end

**Comment by diogenesdauster** [comment]
I'd like to take this

**Comment by tomassirio** [comment]
Pls do!

**Comment by Abhijay007** [comment]
Can I work on this issue? I will add Github workflow to it that will auto automatically update user who the contributor to this repository with their profile pic and profile link

**Comment by tomassirio** [comment]
Oh my god that sounds amazing! Sure do!

**Comment by Jonathanvanhaaften** [comment]
Love to Add

**Comment by tomassirio** [comment]
Pls do
