### ISSUE TITLE
The Command table on the Bot BootUp shows commands that are not there anymore (removemany, addmany)

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/ListBot#65]
![image](https://user-images.githubusercontent.com/19593836/95266604-e97ddd80-0809-11eb-8b3e-13c5677b5dc7.png)

Take them off

**Comment by Toshiuk** [comment]
The command addmany still there yet.
and about the command removemany, is not showing in the list 
![image](https://user-images.githubusercontent.com/8109770/95268249-d7626600-082e-11eb-8211-9feaea779fac.png)

**Comment by Toshiuk** [comment]
Should I remove the command addmany and send a PR?

**Comment by tomassirio** [comment]
Yes please, remove the command and send a PR
