### ISSUE TITLE
README.md is missing time option for polling command

### ISSUE THREAD

**Issue by AldoTu** [tomassirio/ListBot#69]
Polling command accepts a time element for the polling but that is not documented inside the README.md.
Better documentation suggested.

**Comment by AldoTu** [comment]
@tomassirio if ypu assign it to me I can complete it. :)

**Comment by tomassirio** [comment]
Sure buddy. There you go

**Comment by AldoTu** [comment]
Hi @tomassirio! Already uploaded my PR #70. 
Hope you like the changes. :)

**Comment by tomassirio** [comment]
I really liked them! Thanks @AldoTu
