### ISSUE TITLE
Add $remind functionality to list of commands

### ISSUE THREAD

**Issue by AldoTu** [tomassirio/ListBot#76]
Hi @tomassirio, I liked your project and added locally a $remind command so the bot in Discord can remind you of a certain element after n minutes.
If you like it I can pull it for your review. :)

**Comment by tomassirio** [comment]
Yes please! I love it

**Comment by AldoTu** [comment]
@tomassirio already made the PR #77 
Hope you like it (or expecting feedback jejeje)

**Comment by tomassirio** [comment]
closed on [#77](https://github.com/tomassirio/ListBot/pull/77). Adding a new issue to delete the element after the time is over
