### ISSUE TITLE
In the $remind command, the element should be deleted after the time is up. Also it should show a notification for the reminded element

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/ListBot#78]
Comes from issue [#76](https://github.com/tomassirio/ListBot/issues/76)

**Comment by AldoTu** [comment]
Agreed, could you please explain a little bit more how the notification should work?

**Comment by tomassirio** [comment]
My bad on the notifications. I reread the TimeOut section and found the REMINDER message. So that's okay

**Comment by AldoTu** [comment]
Ok :)
Working on the removal of the item.

**Comment by AldoTu** [comment]
@tomassirio already uploaded PR #87
