### ISSUE TITLE
Add the possibility of having Roles on the bot

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/ListBot#80]
Mostly for users and admin purposes

**Comment by rgroves** [comment]
Hey @tomassirio 👋 can you expand upon your initial thought so that we can add details for what exactly is needed here? As it stands I don't think it is very clear.

**Comment by tomassirio** [comment]
I think this issue should be closed. The bot took mostly another orientation and this feature won't be useful. Let's just close the issue
