### ISSUE TITLE
Add a command that only Admins can use $promote

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/ListBot#82]
The command should check if the user calling it is an Admin. It should receive as parameter a user (fe: $promote @tomassirio).

The person that adds ListBot to a server should be the first admin

**Comment by ahmad-reza619** [comment]
Can i take these issue?

**Comment by tomassirio** [comment]
You can sure do. 
Join the [discord](https://discord.gg/hK9EBN) server too

**Comment by ahmad-reza619** [comment]
Sure :)
