### ISSUE TITLE
[Encryption] We need to encrypt the data saved to MongoDb

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/ListBot#84]
Data is private. We need to encrypt the Discord channels, users, and elements added to the list when we are saving them to the Db instance.

A next issue will add a secret key for the Hash function

**Comment by aaronzshey** [comment]
I can work on this!  Can we use bcrypt?

**Comment by tomassirio** [comment]
Sure! I'll assign it to you. There's a [discord](https://discord.gg/59YjSZ) server if you want to join

**Comment by aaronzshey** [comment]
Awesome!  I'll get on it right away.

**Comment by aaronzshey** [comment]
Which file should I start editing?

**Comment by aaronzshey** [comment]
Update: I am going to use crypto instead of bcrypt.

**Comment by tomassirio** [comment]
Sure, I read the article you gave me and seems pretty readable.

**Comment by aaronzshey** [comment]
Cool - we can probably merge this with the secret for encryption issue.

**Comment by sdanpo** [comment]
Hi Tomas,
Another option to encrypt (and still operate over the encrypted data) is to use Kindite.
It is an encryption mechanism which wihtout any code changes completely encrypts the needed fields and allows you to operate on them without any performance hit.

In case you would like to read more https://blog.kindite.com/hubfs/Use%20case%20-%20Hybrid%20B2C%20apps.pdf

**Comment by tomassirio** [comment]
I'm going to read it through out the day. If you think this changes are better than the ones proposed by @CarlyRaeJepsenStan, please debate them with him. Btw, since debating through issues is kind of a hassle (even though it's by far more organized) we are disccussing this changes on the official [discord](https://discord.gg/59YjSZ) server, please come and chat with us

**Comment by aaronzshey** [comment]
@sdanpo While Kindite looks useful and fast, it seems to be a production/business product - you have to pay, and it seems geared to massive server networks.  For our humble uses, I think crypto would work ok.

**Comment by aaronzshey** [comment]
#108
