### ISSUE TITLE
$list command should show the element where the user is and viceversa

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/ListBot#88]
![image](https://user-images.githubusercontent.com/19593836/95518545-ad798280-0999-11eb-9e38-b704fef84d49.png)

Right now the format looks something line:

i - bold(authorName)
_Message_

it should look:

i - bold(Message)
_authorName_

**Comment by rahulpatel596** [comment]
I would like to work on this if still available @tomassirio

**Comment by adhammo** [comment]
this is an easy issue and I already found the solution (just replace name and value). because this is how discord API works. it will make the name bold. can you assign me to this issue?

![image](https://user-images.githubusercontent.com/56611873/95524929-fef23380-09d2-11eb-93d4-c2682bbc6b6b.png)
