### ISSUE TITLE
The bot needs to follow a convention

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/ListBot#97]
@medusalix: 

> - The project should really follow a consistent code style: Semicolons/no semicolons, double quotes/single quotes, let for constant variables, etc... I'd suggest using a combination of Prettier and ESLint. Makes contributing so much easier.

My suggestions would be: No semicolons, single quotes and let for variables.
However, i'm not an experienced Node.js developer. So any suggestions, such as Prettier and ESLint as stated before will be considered

**Comment by anontyro** [comment]
@tomassirio I can add in prettier and eslint if you like. Prettier generally will enforce semicolons and both follow the convention of using `const` over let unless you require mutability which is fairly normal in JavaScript. Single Quotes can be configured however. but it will make it easier in the long term and VS Code does have auto formatting options which is pretty great for this as well

**Comment by tomassirio** [comment]
Sure, i'll assign it to you. Join the discord server so we can keep discussing this with the gang [link](http://www.discord.io/listbot)
